export type DealerSeed = {
  en: string;
  ru: string;
  addressEn: string;
  addressRu: string;
  phone: string;
  logoSeed?: string;
};

/** At least 55 unique dealers for the Dealers directory page. */
export const dealersSeed: DealerSeed[] = [
  {
    en: 'Auto Imperia',
    ru: 'Auto Imperia',
    addressEn: 'Vazha-Pshavela Ave 41, Tbilisi',
    addressRu: 'пр. Важа-Пшавела 41, Тбилиси',
    phone: '995 598 118 744',
    logoSeed: 'auto-imperia',
  },
  {
    en: 'Caucasus Auto',
    ru: 'Кавказ Авто',
    addressEn: 'Rustavi, Red Bridge Highway',
    addressRu: 'Рустави, шоссе Красный мост',
    phone: '995 555 141 920',
    logoSeed: 'caucasus-auto',
  },
  {
    en: 'Worldcars',
    ru: 'Worldcars',
    addressEn: 'Elizbar Mindeli St N4a, Tbilisi',
    addressRu: 'ул. Элизбар Миндели N4a, Тбилиси',
    phone: '995 551 580 191',
    logoSeed: 'worldcars',
  },
  {
    en: 'GLOBAL AUTO TRANSPORTER',
    ru: 'GLOBAL AUTO TRANSPORTER',
    addressEn: 'Saburtalo, Berbuki 10, Tbilisi',
    addressRu: 'Сабуртало, Бербуки 10, Тбилиси',
    phone: '995 555 004 131',
    logoSeed: 'global-auto',
  },
  {
    en: 'AUTO IMPORT GEORGIA',
    ru: 'AUTO IMPORT GEORGIA',
    addressEn: 'Giorgi Saakadze II Exit, Tbilisi',
    addressRu: 'Георгий Саакадзе II выход, Тбилиси',
    phone: '995 579 026 788',
    logoSeed: 'auto-import-ge',
  },
  {
    en: 'Atlas Auto Import',
    ru: 'Atlas Auto Import',
    addressEn: 'George Balanchine St 18, Tbilisi',
    addressRu: 'ул. Джорджа Баланчина 18, Тбилиси',
    phone: '995 579 881 717',
    logoSeed: 'atlas-auto',
  },
  {
    en: 'Trans World Auto',
    ru: 'Trans World Auto',
    addressEn: 'University St 54, Tbilisi',
    addressRu: 'ул. Университетская 54, Тбилиси',
    phone: '995 557 602 208',
    logoSeed: 'transworld',
  },
  {
    en: 'AutoHub Tbilisi',
    ru: 'AutoHub Тбилиси',
    addressEn: 'Chavchavadze Ave 22, Tbilisi',
    addressRu: 'пр. Чавчавадзе 22, Тбилиси',
    phone: '995 555 100 201',
  },
  {
    en: 'Premium Motors Georgia',
    ru: 'Premium Motors Грузия',
    addressEn: 'Pekini Ave 8, Tbilisi',
    addressRu: 'пр. Пекина 8, Тбилиси',
    phone: '995 555 100 202',
  },
  {
    en: 'EuroCar Import',
    ru: 'EuroCar Import',
    addressEn: 'Kakheti Highway 12, Tbilisi',
    addressRu: 'Кахетинское шоссе 12, Тбилиси',
    phone: '995 555 100 203',
  },
  {
    en: 'City Auto Center',
    ru: 'City Auto Center',
    addressEn: 'Aghmashenebeli Ave 140, Tbilisi',
    addressRu: 'пр. Агмашенебели 140, Тбилиси',
    phone: '995 555 100 204',
  },
  {
    en: 'Black Sea Motors',
    ru: 'Black Sea Motors',
    addressEn: 'Rustaveli Ave 45, Batumi',
    addressRu: 'пр. Руставели 45, Батуми',
    phone: '995 555 100 205',
  },
  {
    en: 'Capital Car Showroom',
    ru: 'Capital Car Showroom',
    addressEn: 'Freedom Square 3, Tbilisi',
    addressRu: 'пл. Свободы 3, Тбилиси',
    phone: '995 555 100 206',
  },
  {
    en: 'Drive Georgia',
    ru: 'Drive Georgia',
    addressEn: 'Tsereteli Ave 76, Tbilisi',
    addressRu: 'пр. Церетели 76, Тбилиси',
    phone: '995 555 100 207',
  },
  {
    en: 'Luxury Auto Batumi',
    ru: 'Luxury Auto Батуми',
    addressEn: 'Gorgasali St 15, Batumi',
    addressRu: 'ул. Горгасали 15, Батуми',
    phone: '995 555 100 208',
  },
  {
    en: 'Fast Lane Dealers',
    ru: 'Fast Lane Dealers',
    addressEn: 'Isani, Kakheti Hwy 5, Tbilisi',
    addressRu: 'Исани, Кахетинское ш. 5, Тбилиси',
    phone: '995 555 100 209',
  },
  {
    en: 'Green Wheels EV',
    ru: 'Green Wheels EV',
    addressEn: 'Saburtalo, Vazha-Pshavela 71, Tbilisi',
    addressRu: 'Сабуртало, Важа-Пшавела 71, Тбилиси',
    phone: '995 555 100 210',
  },
  {
    en: 'Classic Garage',
    ru: 'Classic Garage',
    addressEn: 'Vera, Kostava 28, Tbilisi',
    addressRu: 'Вера, Костава 28, Тбилиси',
    phone: '995 555 100 211',
  },
  {
    en: 'Truck & Bus Pro',
    ru: 'Truck & Bus Pro',
    addressEn: 'Lilo Industrial Zone, Tbilisi',
    addressRu: 'промзона Лило, Тбилиси',
    phone: '995 555 100 212',
  },
  {
    en: 'Moto World Georgia',
    ru: 'Moto World Georgia',
    addressEn: 'Digomi, Akhmeteli 9, Tbilisi',
    addressRu: 'Дигоми, Ахметели 9, Тбилиси',
    phone: '995 555 100 213',
  },
  {
    en: 'USA Import Specialists',
    ru: 'USA Import Specialists',
    addressEn: 'Airport Road 4, Tbilisi',
    addressRu: 'Аэропортное шоссе 4, Тбилиси',
    phone: '995 555 100 214',
  },
  {
    en: 'German Auto House',
    ru: 'German Auto House',
    addressEn: 'Vake, Chavchavadze 60, Tbilisi',
    addressRu: 'Ваке, Чавчавадзе 60, Тбилиси',
    phone: '995 555 100 215',
  },
  {
    en: 'Japan Direct Imports',
    ru: 'Japan Direct Imports',
    addressEn: 'Poti Port Zone, Poti',
    addressRu: 'порт Поти, Поти',
    phone: '995 555 100 216',
  },
  {
    en: 'Family Auto Kutaisi',
    ru: 'Family Auto Кутаиси',
    addressEn: 'Rustaveli Ave 12, Kutaisi',
    addressRu: 'пр. Руставели 12, Кутаиси',
    phone: '995 555 100 217',
  },
  {
    en: 'Elite Motors Dubai GE',
    ru: 'Elite Motors Dubai GE',
    addressEn: 'Mtatsminda, Chonkadze 7, Tbilisi',
    addressRu: 'Мтацминда, Чонкадзе 7, Тбилиси',
    phone: '995 555 100 218',
  },
  {
    en: 'Budget Cars Georgia',
    ru: 'Budget Cars Georgia',
    addressEn: 'Gldani, Akhmeteli 33, Tbilisi',
    addressRu: 'Глдани, Ахметели 33, Тбилиси',
    phone: '995 555 100 219',
  },
  {
    en: 'Sport Car Gallery',
    ru: 'Sport Car Gallery',
    addressEn: 'Vake, Abashidze 40, Tbilisi',
    addressRu: 'Ваке, Абашидзе 40, Тбилиси',
    phone: '995 555 100 220',
  },
  {
    en: 'Commercial Fleet Sales',
    ru: 'Commercial Fleet Sales',
    addressEn: 'Samgori Industrial Park, Tbilisi',
    addressRu: 'промпарк Самгори, Тбилиси',
    phone: '995 555 100 221',
  },
  {
    en: 'Hybrid Planet',
    ru: 'Hybrid Planet',
    addressEn: 'Saburtalo, Kazbegi 25, Tbilisi',
    addressRu: 'Сабуртало, Казбеги 25, Тбилиси',
    phone: '995 555 100 222',
  },
  {
    en: 'Vintage Auto Club',
    ru: 'Vintage Auto Club',
    addressEn: 'Sololaki, Betlemi 5, Tbilisi',
    addressRu: 'Сололаки, Бетлеми 5, Тбилиси',
    phone: '995 555 100 223',
  },
  {
    en: 'AutoMax International',
    ru: 'AutoMax International',
    addressEn: 'Didube, Tsereteli 120, Tbilisi',
    addressRu: 'Дидубе, Церетели 120, Тбилиси',
    phone: '995 555 100 224',
  },
  {
    en: 'Caucasus Auto Trade',
    ru: 'Caucasus Auto Trade',
    addressEn: 'Marneuli Highway 8, Tbilisi',
    addressRu: 'Марнеульское шоссе 8, Тбилиси',
    phone: '995 555 100 225',
  },
  {
    en: 'Smart Mobility Hub',
    ru: 'Smart Mobility Hub',
    addressEn: 'Saburtalo, Bakhtrioni 16, Tbilisi',
    addressRu: 'Сабуртало, Бахтриони 16, Тбилиси',
    phone: '995 555 100 226',
  },
  {
    en: 'Royal Auto Palace',
    ru: 'Royal Auto Palace',
    addressEn: 'Vake, Nino Chkheidze 11, Tbilisi',
    addressRu: 'Ваке, Нино Чхеидзе 11, Тбилиси',
    phone: '995 555 100 227',
  },
  {
    en: 'NextGen Motors',
    ru: 'NextGen Motors',
    addressEn: 'Didi Digomi, 4th District, Tbilisi',
    addressRu: 'Диди Дигоми, 4 мкр., Тбилиси',
    phone: '995 555 100 228',
  },
  {
    en: 'AutoExpress Georgia',
    ru: 'AutoExpress Georgia',
    addressEn: 'Ortachala, Gorgasali 88, Tbilisi',
    addressRu: 'Ортачала, Горгасали 88, Тбилиси',
    phone: '995 555 100 229',
  },
  {
    en: 'ProDrive Showroom',
    ru: 'ProDrive Showroom',
    addressEn: 'Isani, Ketevan Tsamebuli 55, Tbilisi',
    addressRu: 'Исани, Кетеван Цамебули 55, Тбилиси',
    phone: '995 555 100 230',
  },
  {
    en: 'Alpine Motors GE',
    ru: 'Alpine Motors GE',
    addressEn: 'Batumi Boulevard 20, Batumi',
    addressRu: 'Батумский бульвар 20, Батуми',
    phone: '995 555 100 231',
  },
  {
    en: 'Caspian Auto Trade',
    ru: 'Caspian Auto Trade',
    addressEn: 'Poti Free Zone, Poti',
    addressRu: 'Свободная зона Поти, Поти',
    phone: '995 555 100 232',
  },
  {
    en: 'Tbilisi Car Market',
    ru: 'Tbilisi Car Market',
    addressEn: 'Eliava Market Area, Tbilisi',
    addressRu: 'рынок Элиава, Тбилиси',
    phone: '995 555 100 233',
  },
  {
    en: 'Skyline Auto',
    ru: 'Skyline Auto',
    addressEn: 'Digomi Massif 3, Tbilisi',
    addressRu: 'Дигоми массив 3, Тбилиси',
    phone: '995 555 100 234',
  },
  {
    en: 'Metro Motors',
    ru: 'Metro Motors',
    addressEn: 'Station Square 2, Tbilisi',
    addressRu: 'Вокзальная площадь 2, Тбилиси',
    phone: '995 555 100 235',
  },
  {
    en: 'Pacific Imports GE',
    ru: 'Pacific Imports GE',
    addressEn: 'Batumi Port Area, Batumi',
    addressRu: 'порт Батуми, Батуми',
    phone: '995 555 100 236',
  },
  {
    en: 'Kartveli Auto',
    ru: 'Картвели Авто',
    addressEn: 'Rustavi Central, Rustavi',
    addressRu: 'центр Рустави, Рустави',
    phone: '995 555 100 237',
  },
  {
    en: 'Nordic Cars Georgia',
    ru: 'Nordic Cars Georgia',
    addressEn: 'Saburtalo, Nutsubidze 14, Tbilisi',
    addressRu: 'Сабуртало, Нуцубидзе 14, Тбилиси',
    phone: '995 555 100 238',
  },
  {
    en: 'Horizon Auto Group',
    ru: 'Horizon Auto Group',
    addressEn: 'Kutaisi Industrial Zone, Kutaisi',
    addressRu: 'промзона Кутаиси, Кутаиси',
    phone: '995 555 100 239',
  },
  {
    en: 'Prime Select Autos',
    ru: 'Prime Select Autos',
    addressEn: 'Vake, Melikishvili 10, Tbilisi',
    addressRu: 'Ваке, Меликишвили 10, Тбилиси',
    phone: '995 555 100 240',
  },
  {
    en: 'AutoPlaza East',
    ru: 'AutoPlaza East',
    addressEn: 'Kakheti Hwy 28, Tbilisi',
    addressRu: 'Кахетинское шоссе 28, Тбилиси',
    phone: '995 555 100 241',
  },
  {
    en: 'Star Motors GE',
    ru: 'Star Motors GE',
    addressEn: 'Gldani, Temka 6, Tbilisi',
    addressRu: 'Глдани, Темка 6, Тбилиси',
    phone: '995 555 100 242',
  },
  {
    en: 'Velocity Auto',
    ru: 'Velocity Auto',
    addressEn: 'Isani, Navtlugi 3, Tbilisi',
    addressRu: 'Исани, Навтлуги 3, Тбилиси',
    phone: '995 555 100 243',
  },
  {
    en: 'Grand Touring Cars',
    ru: 'Grand Touring Cars',
    addressEn: 'Mtatsminda, Chonkadze 19, Tbilisi',
    addressRu: 'Мтацминда, Чонкадзе 19, Тбилиси',
    phone: '995 555 100 244',
  },
  {
    en: 'Fleet Masters',
    ru: 'Fleet Masters',
    addressEn: 'Lilo 2, Warehouse 14, Tbilisi',
    addressRu: 'Лило 2, склад 14, Тбилиси',
    phone: '995 555 100 245',
  },
  {
    en: 'EcoDrive Motors',
    ru: 'EcoDrive Motors',
    addressEn: 'Saburtalo, Pekini 29, Tbilisi',
    addressRu: 'Сабуртало, Пекина 29, Тбилиси',
    phone: '995 555 100 246',
  },
  {
    en: 'Black Sea Imports',
    ru: 'Black Sea Imports',
    addressEn: 'Batumi New Boulevard 8, Batumi',
    addressRu: 'Новый бульвар 8, Батуми',
    phone: '995 555 100 247',
  },
  {
    en: 'Capital Fleet Center',
    ru: 'Capital Fleet Center',
    addressEn: 'Didube Plaza, Tbilisi',
    addressRu: 'Дидубе Плаза, Тбилиси',
    phone: '995 555 100 248',
  },
];

/** @deprecated Prefer dealersSeed — kept for older seed imports */
export const dealerNames = dealersSeed.map(({ en, ru }) => ({ en, ru }));
