export type CountrySeed = {
  nameEn: string;
  nameRu: string;
  code: string;
  cities: Array<{ nameEn: string; nameRu: string }>;
};

export const countries: CountrySeed[] = [
  {
    nameEn: 'Georgia',
    nameRu: 'Грузия',
    code: 'GE',
    cities: [
      { nameEn: 'Tbilisi', nameRu: 'Тбилиси' },
      { nameEn: 'Batumi', nameRu: 'Батуми' },
      { nameEn: 'Kutaisi', nameRu: 'Кутаиси' },
      { nameEn: 'Rustavi', nameRu: 'Рустави' },
      { nameEn: 'Borjomi', nameRu: 'Боржоми' },
      { nameEn: 'Gori', nameRu: 'Гори' },
      { nameEn: 'Zugdidi', nameRu: 'Зугдиди' },
      { nameEn: 'Poti', nameRu: 'Поти' },
      { nameEn: 'Telavi', nameRu: 'Телави' },
      { nameEn: 'Mtskheta', nameRu: 'Мцхета' },
      { nameEn: 'Akhaltsikhe', nameRu: 'Ахалцихе' },
      { nameEn: 'Senaki', nameRu: 'Сенаки' },
      { nameEn: 'Marneuli', nameRu: 'Марнеули' },
      { nameEn: 'Kobuleti', nameRu: 'Кобулети' },
    ],
  },
  {
    nameEn: 'Germany',
    nameRu: 'Германия',
    code: 'DE',
    cities: [
      { nameEn: 'Berlin', nameRu: 'Берлин' },
      { nameEn: 'Munich', nameRu: 'Мюнхен' },
      { nameEn: 'Hamburg', nameRu: 'Гамбург' },
      { nameEn: 'Frankfurt', nameRu: 'Франкфурт' },
      { nameEn: 'Cologne', nameRu: 'Кёльн' },
      { nameEn: 'Stuttgart', nameRu: 'Штутгарт' },
      { nameEn: 'Düsseldorf', nameRu: 'Дüsseldorf' },
      { nameEn: 'Dortmund', nameRu: 'Дортмунд' },
      { nameEn: 'Essen', nameRu: 'Эссен' },
      { nameEn: 'Leipzig', nameRu: 'Лейпциг' },
    ],
  },
  {
    nameEn: 'USA',
    nameRu: 'США',
    code: 'US',
    cities: [
      { nameEn: 'New York', nameRu: 'Нью-Йорк' },
      { nameEn: 'Los Angeles', nameRu: 'Лос-Анджелес' },
      { nameEn: 'Chicago', nameRu: 'Чикаго' },
      { nameEn: 'Houston', nameRu: 'Хьюстон' },
      { nameEn: 'Phoenix', nameRu: 'Финикс' },
      { nameEn: 'Philadelphia', nameRu: 'Филадельфия' },
      { nameEn: 'San Antonio', nameRu: 'Сан-Антонио' },
      { nameEn: 'San Diego', nameRu: 'Сан-Дiego' },
      { nameEn: 'Dallas', nameRu: 'Даллас' },
      { nameEn: 'Miami', nameRu: 'Майами' },
    ],
  },
  {
    nameEn: 'Japan',
    nameRu: 'Япония',
    code: 'JP',
    cities: [
      { nameEn: 'Tokyo', nameRu: 'Токио' },
      { nameEn: 'Osaka', nameRu: 'Осака' },
      { nameEn: 'Yokohama', nameRu: 'Иокогама' },
      { nameEn: 'Nagoya', nameRu: 'Нагоя' },
      { nameEn: 'Sapporo', nameRu: 'Саппoro' },
      { nameEn: 'Fukuoka', nameRu: 'Фukuoka' },
      { nameEn: 'Kobe', nameRu: 'Кobe' },
      { nameEn: 'Kyoto', nameRu: 'Киото' },
    ],
  },
  {
    nameEn: 'South Korea',
    nameRu: 'Южная Корея',
    code: 'KR',
    cities: [
      { nameEn: 'Seoul', nameRu: 'Сеул' },
      { nameEn: 'Busan', nameRu: 'Пусан' },
      { nameEn: 'Incheon', nameRu: 'Инчхон' },
      { nameEn: 'Daegu', nameRu: 'Тэгу' },
      { nameEn: 'Daejeon', nameRu: 'Тэджон' },
      { nameEn: 'Gwangju', nameRu: 'Кwangju' },
    ],
  },
  {
    nameEn: 'United Kingdom',
    nameRu: 'Великобритания',
    code: 'GB',
    cities: [
      { nameEn: 'London', nameRu: 'Лондон' },
      { nameEn: 'Manchester', nameRu: 'Манчестер' },
      { nameEn: 'Birmingham', nameRu: 'Бирмингем' },
      { nameEn: 'Liverpool', nameRu: 'Ливерпуль' },
      { nameEn: 'Edinburgh', nameRu: 'Эдинбург' },
      { nameEn: 'Glasgow', nameRu: 'Глазго' },
    ],
  },
  {
    nameEn: 'France',
    nameRu: 'Франция',
    code: 'FR',
    cities: [
      { nameEn: 'Paris', nameRu: 'Париж' },
      { nameEn: 'Marseille', nameRu: 'Марсель' },
      { nameEn: 'Lyon', nameRu: 'Лион' },
      { nameEn: 'Toulouse', nameRu: 'Тулуза' },
      { nameEn: 'Nice', nameRu: 'Ницца' },
      { nameEn: 'Bordeaux', nameRu: 'Бордо' },
    ],
  },
  {
    nameEn: 'Italy',
    nameRu: 'Италия',
    code: 'IT',
    cities: [
      { nameEn: 'Rome', nameRu: 'Рим' },
      { nameEn: 'Milan', nameRu: 'Милан' },
      { nameEn: 'Naples', nameRu: 'Неаполь' },
      { nameEn: 'Turin', nameRu: 'Турин' },
      { nameEn: 'Florence', nameRu: 'Флоренция' },
      { nameEn: 'Bologna', nameRu: 'Болонья' },
    ],
  },
  {
    nameEn: 'Spain',
    nameRu: 'Испания',
    code: 'ES',
    cities: [
      { nameEn: 'Madrid', nameRu: 'Мадрид' },
      { nameEn: 'Barcelona', nameRu: 'Барселона' },
      { nameEn: 'Valencia', nameRu: 'Валенсия' },
      { nameEn: 'Seville', nameRu: 'Севилья' },
      { nameEn: 'Bilbao', nameRu: 'Бильbao' },
    ],
  },
  {
    nameEn: 'Turkey',
    nameRu: 'Турция',
    code: 'TR',
    cities: [
      { nameEn: 'Istanbul', nameRu: 'Стамбул' },
      { nameEn: 'Ankara', nameRu: 'Анкара' },
      { nameEn: 'Izmir', nameRu: 'Измир' },
      { nameEn: 'Bursa', nameRu: 'Бурса' },
      { nameEn: 'Antalya', nameRu: 'Антalya' },
    ],
  },
  {
    nameEn: 'UAE',
    nameRu: 'ОАЭ',
    code: 'AE',
    cities: [
      { nameEn: 'Dubai', nameRu: 'Дубай' },
      { nameEn: 'Abu Dhabi', nameRu: 'Абу-Даби' },
      { nameEn: 'Sharjah', nameRu: 'Шарджа' },
      { nameEn: 'Ajman', nameRu: 'Ajman' },
    ],
  },
  {
    nameEn: 'China',
    nameRu: 'Китай',
    code: 'CN',
    cities: [
      { nameEn: 'Shanghai', nameRu: 'Шанхай' },
      { nameEn: 'Beijing', nameRu: 'Пекин' },
      { nameEn: 'Guangzhou', nameRu: 'Гуанчzhou' },
      { nameEn: 'Shenzhen', nameRu: 'Шэньчжэнь' },
      { nameEn: 'Chengdu', nameRu: 'Чэнду' },
    ],
  },
  {
    nameEn: 'Poland',
    nameRu: 'Польша',
    code: 'PL',
    cities: [
      { nameEn: 'Warsaw', nameRu: 'Варшава' },
      { nameEn: 'Krakow', nameRu: 'Краков' },
      { nameEn: 'Wroclaw', nameRu: 'Вроцлав' },
      { nameEn: 'Gdansk', nameRu: 'Гданьск' },
      { nameEn: 'Poznan', nameRu: 'Познань' },
    ],
  },
  {
    nameEn: 'Czech Republic',
    nameRu: 'Чехия',
    code: 'CZ',
    cities: [
      { nameEn: 'Prague', nameRu: 'Прага' },
      { nameEn: 'Brno', nameRu: 'Брно' },
      { nameEn: 'Ostrava', nameRu: 'Ostrava' },
    ],
  },
  {
    nameEn: 'Sweden',
    nameRu: 'Швеция',
    code: 'SE',
    cities: [
      { nameEn: 'Stockholm', nameRu: 'Стокгольм' },
      { nameEn: 'Gothenburg', nameRu: 'Гёteborg' },
      { nameEn: 'Malmo', nameRu: 'Мальмё' },
    ],
  },
  {
    nameEn: 'Netherlands',
    nameRu: 'Нидерланды',
    code: 'NL',
    cities: [
      { nameEn: 'Amsterdam', nameRu: 'Амстердам' },
      { nameEn: 'Rotterdam', nameRu: 'Ротterdam' },
      { nameEn: 'The Hague', nameRu: 'Гаага' },
      { nameEn: 'Utrecht', nameRu: 'Utrecht' },
    ],
  },
  {
    nameEn: 'Canada',
    nameRu: 'Канада',
    code: 'CA',
    cities: [
      { nameEn: 'Toronto', nameRu: 'Торонто' },
      { nameEn: 'Vancouver', nameRu: 'Ванкувер' },
      { nameEn: 'Montreal', nameRu: 'Монреаль' },
      { nameEn: 'Calgary', nameRu: 'Calgary' },
    ],
  },
  {
    nameEn: 'Australia',
    nameRu: 'Австралия',
    code: 'AU',
    cities: [
      { nameEn: 'Sydney', nameRu: 'Сидней' },
      { nameEn: 'Melbourne', nameRu: 'Мельбourn' },
      { nameEn: 'Brisbane', nameRu: 'Brisbane' },
      { nameEn: 'Perth', nameRu: 'Perth' },
    ],
  },
  {
    nameEn: 'Armenia',
    nameRu: 'Армения',
    code: 'AM',
    cities: [
      { nameEn: 'Yerevan', nameRu: 'Ереван' },
      { nameEn: 'Gyumri', nameRu: 'Gyumri' },
      { nameEn: 'Vanadzor', nameRu: 'Vanadzor' },
    ],
  },
  {
    nameEn: 'Azerbaijan',
    nameRu: 'Азербайджан',
    code: 'AZ',
    cities: [
      { nameEn: 'Baku', nameRu: 'Baku' },
      { nameEn: 'Ganja', nameRu: 'Ganja' },
      { nameEn: 'Sumqayit', nameRu: 'Sumqayit' },
    ],
  },
];
