export type ManufacturerSeed = {
  nameEn: string;
  nameRu: string;
  country: string;
  models: Array<{ nameEn: string; nameRu: string }>;
};

export const manufacturers: ManufacturerSeed[] = [
  {
    nameEn: 'Toyota',
    nameRu: 'Тойота',
    country: 'Japan',
    models: [
      { nameEn: 'Camry', nameRu: 'Камри' },
      { nameEn: 'Corolla', nameRu: 'Королла' },
      { nameEn: 'RAV4', nameRu: 'РAV4' },
      { nameEn: 'Land Cruiser', nameRu: 'Ленд Крузер' },
      { nameEn: 'Prius', nameRu: 'Приус' },
      { nameEn: 'Highlander', nameRu: 'Хайлендер' },
      { nameEn: 'Yaris', nameRu: 'Ярис' },
      { nameEn: 'Supra', nameRu: 'Супра' },
      { nameEn: 'Raize', nameRu: 'Райз' },
      { nameEn: 'C-HR', nameRu: 'C-HR' },
      { nameEn: '4Runner', nameRu: '4Runner' },
      { nameEn: 'Tundra', nameRu: 'Tundra' },
      { nameEn: 'Tacoma', nameRu: 'Tacoma' },
      { nameEn: 'Sienna', nameRu: 'Sienna' },
      { nameEn: 'Avalon', nameRu: 'Avalon' },
      { nameEn: 'GR86', nameRu: 'GR86' },
      { nameEn: 'bZ4X', nameRu: 'bZ4X' },
      { nameEn: 'Hilux', nameRu: 'Hilux' },
    ],
  },
  {
    nameEn: 'BMW',
    nameRu: 'БМВ',
    country: 'Germany',
    models: [
      { nameEn: '1 Series', nameRu: '1 Серия' },
      { nameEn: '2 Series', nameRu: '2 Серия' },
      { nameEn: '3 Series', nameRu: '3 Серия' },
      { nameEn: '4 Series', nameRu: '4 Серия' },
      { nameEn: '5 Series', nameRu: '5 Серия' },
      { nameEn: '7 Series', nameRu: '7 Серия' },
      { nameEn: '8 Series', nameRu: '8 Серия' },
      { nameEn: 'X1', nameRu: 'X1' },
      { nameEn: 'X3', nameRu: 'X3' },
      { nameEn: 'X5', nameRu: 'X5' },
      { nameEn: 'X6', nameRu: 'X6' },
      { nameEn: 'X7', nameRu: 'X7' },
      { nameEn: 'M3', nameRu: 'M3' },
      { nameEn: 'M4', nameRu: 'M4' },
      { nameEn: 'M5', nameRu: 'M5' },
      { nameEn: 'i4', nameRu: 'i4' },
      { nameEn: 'iX', nameRu: 'iX' },
      { nameEn: 'Z4', nameRu: 'Z4' },
    ],
  },
  {
    nameEn: 'Mercedes-Benz',
    nameRu: 'Мерседес-Бенц',
    country: 'Germany',
    models: [
      { nameEn: 'A-Class', nameRu: 'A-Класс' },
      { nameEn: 'C-Class', nameRu: 'C-Класс' },
      { nameEn: 'E-Class', nameRu: 'E-Класс' },
      { nameEn: 'S-Class', nameRu: 'S-Класс' },
      { nameEn: 'CLA', nameRu: 'CLA' },
      { nameEn: 'CLS', nameRu: 'CLS' },
      { nameEn: 'GLA', nameRu: 'GLA' },
      { nameEn: 'GLC', nameRu: 'GLC' },
      { nameEn: 'GLE', nameRu: 'GLE' },
      { nameEn: 'GLS', nameRu: 'GLS' },
      { nameEn: 'G-Class', nameRu: 'G-Класс' },
      { nameEn: 'Actros', nameRu: 'Актros' },
      { nameEn: 'Sprinter', nameRu: 'Спринтер' },
      { nameEn: 'Vito', nameRu: 'Vito' },
      { nameEn: 'EQE', nameRu: 'EQE' },
      { nameEn: 'EQS', nameRu: 'EQS' },
      { nameEn: 'AMG GT', nameRu: 'AMG GT' },
    ],
  },
  {
    nameEn: 'Audi',
    nameRu: 'Ауди',
    country: 'Germany',
    models: [
      { nameEn: 'A1', nameRu: 'A1' },
      { nameEn: 'A3', nameRu: 'A3' },
      { nameEn: 'A4', nameRu: 'A4' },
      { nameEn: 'A5', nameRu: 'A5' },
      { nameEn: 'A6', nameRu: 'A6' },
      { nameEn: 'A7', nameRu: 'A7' },
      { nameEn: 'A8', nameRu: 'A8' },
      { nameEn: 'Q2', nameRu: 'Q2' },
      { nameEn: 'Q3', nameRu: 'Q3' },
      { nameEn: 'Q5', nameRu: 'Q5' },
      { nameEn: 'Q7', nameRu: 'Q7' },
      { nameEn: 'Q8', nameRu: 'Q8' },
      { nameEn: 'e-tron', nameRu: 'e-tron' },
      { nameEn: 'RS6', nameRu: 'RS6' },
      { nameEn: 'TT', nameRu: 'TT' },
      { nameEn: 'R8', nameRu: 'R8' },
    ],
  },
  {
    nameEn: 'Volkswagen',
    nameRu: 'Фольксваген',
    country: 'Germany',
    models: [
      { nameEn: 'Golf', nameRu: 'Гольф' },
      { nameEn: 'Passat', nameRu: 'Пассат' },
      { nameEn: 'Tiguan', nameRu: 'Тигуан' },
      { nameEn: 'Polo', nameRu: 'Поло' },
      { nameEn: 'Touareg', nameRu: 'Туарег' },
      { nameEn: 'Jetta', nameRu: 'Jetta' },
      { nameEn: 'Arteon', nameRu: 'Arteon' },
      { nameEn: 'T-Roc', nameRu: 'T-Roc' },
      { nameEn: 'ID.4', nameRu: 'ID.4' },
      { nameEn: 'Transporter', nameRu: 'Transporter' },
      { nameEn: 'Caddy', nameRu: 'Caddy' },
      { nameEn: 'Amarok', nameRu: 'Amarok' },
    ],
  },
  {
    nameEn: 'Hyundai',
    nameRu: 'Хёндай',
    country: 'South Korea',
    models: [
      { nameEn: 'Elantra', nameRu: 'Элантра' },
      { nameEn: 'Sonata', nameRu: 'Соната' },
      { nameEn: 'Tucson', nameRu: 'Туссан' },
      { nameEn: 'Santa Fe', nameRu: 'Санта Фе' },
      { nameEn: 'Accent', nameRu: 'Акцент' },
      { nameEn: 'Creta', nameRu: 'Крета' },
      { nameEn: 'Palisade', nameRu: 'Palisade' },
      { nameEn: 'Kona', nameRu: 'Kona' },
      { nameEn: 'Ioniq 5', nameRu: 'Ioniq 5' },
      { nameEn: 'Ioniq 6', nameRu: 'Ioniq 6' },
      { nameEn: 'Staria', nameRu: 'Staria' },
      { nameEn: 'Venue', nameRu: 'Venue' },
    ],
  },
  {
    nameEn: 'Kia',
    nameRu: 'Киа',
    country: 'South Korea',
    models: [
      { nameEn: 'Sportage', nameRu: 'Спортейдж' },
      { nameEn: 'Sorento', nameRu: 'Соренто' },
      { nameEn: 'Rio', nameRu: 'Рио' },
      { nameEn: 'Cerato', nameRu: 'Церато' },
      { nameEn: 'Seltos', nameRu: 'Селтос' },
      { nameEn: 'K5', nameRu: 'K5' },
      { nameEn: 'Stinger', nameRu: 'Stinger' },
      { nameEn: 'Carnival', nameRu: 'Carnival' },
      { nameEn: 'EV6', nameRu: 'EV6' },
      { nameEn: 'Niro', nameRu: 'Niro' },
      { nameEn: 'Telluride', nameRu: 'Telluride' },
    ],
  },
  {
    nameEn: 'Nissan',
    nameRu: 'Ниссан',
    country: 'Japan',
    models: [
      { nameEn: 'Juke', nameRu: 'Джук' },
      { nameEn: 'Qashqai', nameRu: 'Кашкай' },
      { nameEn: 'X-Trail', nameRu: 'Х-Трейл' },
      { nameEn: 'GT-R', nameRu: 'GT-R' },
      { nameEn: 'Patrol', nameRu: 'Патрол' },
      { nameEn: 'March', nameRu: 'Марч' },
      { nameEn: 'Altima', nameRu: 'Altima' },
      { nameEn: 'Sentra', nameRu: 'Sentra' },
      { nameEn: 'Murano', nameRu: 'Murano' },
      { nameEn: 'Pathfinder', nameRu: 'Pathfinder' },
      { nameEn: 'Leaf', nameRu: 'Leaf' },
      { nameEn: 'Navara', nameRu: 'Navara' },
      { nameEn: '370Z', nameRu: '370Z' },
    ],
  },
  {
    nameEn: 'Honda',
    nameRu: 'Хонда',
    country: 'Japan',
    models: [
      { nameEn: 'Civic', nameRu: 'Цивик' },
      { nameEn: 'Accord', nameRu: 'Аккорд' },
      { nameEn: 'CR-V', nameRu: 'CR-V' },
      { nameEn: 'HR-V', nameRu: 'HR-V' },
      { nameEn: 'Fit', nameRu: 'Фит' },
      { nameEn: 'Pilot', nameRu: 'Pilot' },
      { nameEn: 'Odyssey', nameRu: 'Odyssey' },
      { nameEn: 'Ridgeline', nameRu: 'Ridgeline' },
      { nameEn: 'e:Ny1', nameRu: 'e:Ny1' },
    ],
  },
  {
    nameEn: 'Ford',
    nameRu: 'Форд',
    country: 'USA',
    models: [
      { nameEn: 'Focus', nameRu: 'Фокус' },
      { nameEn: 'Mustang', nameRu: 'Мустанг' },
      { nameEn: 'Explorer', nameRu: 'Эксплорер' },
      { nameEn: 'Escape', nameRu: 'Эскейп' },
      { nameEn: 'F-150', nameRu: 'F-150' },
      { nameEn: 'Bronco', nameRu: 'Bronco' },
      { nameEn: 'Edge', nameRu: 'Edge' },
      { nameEn: 'Ranger', nameRu: 'Ranger' },
      { nameEn: 'Transit', nameRu: 'Transit' },
      { nameEn: 'Mach-E', nameRu: 'Mach-E' },
      { nameEn: 'Puma', nameRu: 'Puma' },
      { nameEn: 'Kuga', nameRu: 'Kuga' },
    ],
  },
  {
    nameEn: 'Chevrolet',
    nameRu: 'Шевроле',
    country: 'USA',
    models: [
      { nameEn: 'Camaro', nameRu: 'Камаро' },
      { nameEn: 'Malibu', nameRu: 'Малибу' },
      { nameEn: 'Tahoe', nameRu: 'Тахо' },
      { nameEn: 'Corvette', nameRu: 'Корветт' },
      { nameEn: 'Silverado', nameRu: 'Silverado' },
      { nameEn: 'Equinox', nameRu: 'Equinox' },
      { nameEn: 'Traverse', nameRu: 'Traverse' },
      { nameEn: 'Suburban', nameRu: 'Suburban' },
      { nameEn: 'Bolt EV', nameRu: 'Bolt EV' },
      { nameEn: 'Colorado', nameRu: 'Colorado' },
    ],
  },
  {
    nameEn: 'Mitsubishi',
    nameRu: 'Мицубиси',
    country: 'Japan',
    models: [
      { nameEn: 'Pajero', nameRu: 'Паджеро' },
      { nameEn: 'Outlander', nameRu: 'Аутлендер' },
      { nameEn: 'Lancer', nameRu: 'Лансер' },
      { nameEn: 'ASX', nameRu: 'ASX' },
      { nameEn: 'Eclipse Cross', nameRu: 'Eclipse Cross' },
      { nameEn: 'L200', nameRu: 'L200' },
      { nameEn: 'Mirage', nameRu: 'Mirage' },
    ],
  },
  {
    nameEn: 'Lexus',
    nameRu: 'Лексус',
    country: 'Japan',
    models: [
      { nameEn: 'RX', nameRu: 'RX' },
      { nameEn: 'ES', nameRu: 'ES' },
      { nameEn: 'NX', nameRu: 'NX' },
      { nameEn: 'LX', nameRu: 'LX' },
      { nameEn: 'IS', nameRu: 'IS' },
      { nameEn: 'GX', nameRu: 'GX' },
      { nameEn: 'UX', nameRu: 'UX' },
      { nameEn: 'LC', nameRu: 'LC' },
      { nameEn: 'RZ', nameRu: 'RZ' },
    ],
  },
  {
    nameEn: 'Mazda',
    nameRu: 'Мазда',
    country: 'Japan',
    models: [
      { nameEn: 'CX-3', nameRu: 'CX-3' },
      { nameEn: 'CX-5', nameRu: 'CX-5' },
      { nameEn: 'CX-9', nameRu: 'CX-9' },
      { nameEn: 'CX-30', nameRu: 'CX-30' },
      { nameEn: 'CX-60', nameRu: 'CX-60' },
      { nameEn: 'Mazda 2', nameRu: 'Мазда 2' },
      { nameEn: 'Mazda 3', nameRu: 'Мазда 3' },
      { nameEn: 'Mazda 6', nameRu: 'Мазда 6' },
      { nameEn: 'MX-5', nameRu: 'MX-5' },
      { nameEn: 'BT-50', nameRu: 'BT-50' },
    ],
  },
  {
    nameEn: 'Subaru',
    nameRu: 'Субару',
    country: 'Japan',
    models: [
      { nameEn: 'Forester', nameRu: 'Форестер' },
      { nameEn: 'Outback', nameRu: 'Аутбэк' },
      { nameEn: 'Impreza', nameRu: 'Импреза' },
      { nameEn: 'WRX', nameRu: 'WRX' },
      { nameEn: 'Crosstrek', nameRu: 'Crosstrek' },
      { nameEn: 'Ascent', nameRu: 'Ascent' },
      { nameEn: 'Legacy', nameRu: 'Legacy' },
      { nameEn: 'BRZ', nameRu: 'BRZ' },
    ],
  },
  {
    nameEn: 'Volvo',
    nameRu: 'Вольво',
    country: 'Sweden',
    models: [
      { nameEn: 'XC40', nameRu: 'XC40' },
      { nameEn: 'XC60', nameRu: 'XC60' },
      { nameEn: 'XC90', nameRu: 'XC90' },
      { nameEn: 'S60', nameRu: 'S60' },
      { nameEn: 'S90', nameRu: 'S90' },
      { nameEn: 'V60', nameRu: 'V60' },
      { nameEn: 'V90', nameRu: 'V90' },
      { nameEn: 'C40', nameRu: 'C40' },
      { nameEn: 'FH12', nameRu: 'FH12' },
      { nameEn: 'FH16', nameRu: 'FH16' },
      { nameEn: 'FM', nameRu: 'FM' },
    ],
  },
  {
    nameEn: 'Land Rover',
    nameRu: 'Ленд Ровер',
    country: 'UK',
    models: [
      { nameEn: 'Range Rover', nameRu: 'Рэйндж Ровер' },
      { nameEn: 'Range Rover Sport', nameRu: 'Рэйндж Ровер Спорт' },
      { nameEn: 'Range Rover Evoque', nameRu: 'Evoque' },
      { nameEn: 'Discovery', nameRu: 'Дискавери' },
      { nameEn: 'Discovery Sport', nameRu: 'Discovery Sport' },
      { nameEn: 'Defender', nameRu: 'Дефендер' },
      { nameEn: 'Velar', nameRu: 'Velar' },
    ],
  },
  {
    nameEn: 'Jeep',
    nameRu: 'Джип',
    country: 'USA',
    models: [
      { nameEn: 'Wrangler', nameRu: 'Рэнглер' },
      { nameEn: 'Grand Cherokee', nameRu: 'Гранд Чероки' },
      { nameEn: 'Compass', nameRu: 'Компас' },
      { nameEn: 'Renegade', nameRu: 'Ренегат' },
      { nameEn: 'Cherokee', nameRu: 'Cherokee' },
      { nameEn: 'Gladiator', nameRu: 'Gladiator' },
      { nameEn: 'Wagoneer', nameRu: 'Wagoneer' },
    ],
  },
  {
    nameEn: 'Porsche',
    nameRu: 'Порше',
    country: 'Germany',
    models: [
      { nameEn: '911', nameRu: '911' },
      { nameEn: 'Cayenne', nameRu: 'Кайенн' },
      { nameEn: 'Macan', nameRu: 'Макан' },
      { nameEn: 'Panamera', nameRu: 'Панамера' },
      { nameEn: 'Taycan', nameRu: 'Taycan' },
      { nameEn: '718 Boxster', nameRu: '718 Boxster' },
      { nameEn: '718 Cayman', nameRu: '718 Cayman' },
    ],
  },
  {
    nameEn: 'Tesla',
    nameRu: 'Тесла',
    country: 'USA',
    models: [
      { nameEn: 'Model 3', nameRu: 'Модель 3' },
      { nameEn: 'Model Y', nameRu: 'Модель Y' },
      { nameEn: 'Model S', nameRu: 'Модель S' },
      { nameEn: 'Model X', nameRu: 'Модель X' },
      { nameEn: 'Cybertruck', nameRu: 'Cybertruck' },
    ],
  },
  {
    nameEn: 'Renault',
    nameRu: 'Рeno',
    country: 'France',
    models: [
      { nameEn: 'Clio', nameRu: 'Clio' },
      { nameEn: 'Megane', nameRu: 'Megane' },
      { nameEn: 'Captur', nameRu: 'Captur' },
      { nameEn: 'Kadjar', nameRu: 'Kadjar' },
      { nameEn: 'Arkana', nameRu: 'Arkana' },
      { nameEn: 'Duster', nameRu: 'Duster' },
      { nameEn: 'Koleos', nameRu: 'Koleos' },
      { nameEn: 'Talisman', nameRu: 'Talisman' },
      { nameEn: 'Master', nameRu: 'Master' },
      { nameEn: 'Zoe', nameRu: 'Zoe' },
    ],
  },
  {
    nameEn: 'Peugeot',
    nameRu: 'Peugeot',
    country: 'France',
    models: [
      { nameEn: '208', nameRu: '208' },
      { nameEn: '308', nameRu: '308' },
      { nameEn: '508', nameRu: '508' },
      { nameEn: '2008', nameRu: '2008' },
      { nameEn: '3008', nameRu: '3008' },
      { nameEn: '5008', nameRu: '5008' },
      { nameEn: 'Partner', nameRu: 'Partner' },
      { nameEn: 'Expert', nameRu: 'Expert' },
      { nameEn: 'Rifter', nameRu: 'Rifter' },
    ],
  },
  {
    nameEn: 'Citroen',
    nameRu: 'Citroen',
    country: 'France',
    models: [
      { nameEn: 'C3', nameRu: 'C3' },
      { nameEn: 'C4', nameRu: 'C4' },
      { nameEn: 'C5 Aircross', nameRu: 'C5 Aircross' },
      { nameEn: 'Berlingo', nameRu: 'Berlingo' },
      { nameEn: 'Jumper', nameRu: 'Jumper' },
      { nameEn: 'Ami', nameRu: 'Ami' },
    ],
  },
  {
    nameEn: 'Fiat',
    nameRu: 'Fiat',
    country: 'Italy',
    models: [
      { nameEn: '500', nameRu: '500' },
      { nameEn: 'Panda', nameRu: 'Panda' },
      { nameEn: 'Tipo', nameRu: 'Tipo' },
      { nameEn: '500X', nameRu: '500X' },
      { nameEn: 'Ducato', nameRu: 'Ducato' },
      { nameEn: 'Doblo', nameRu: 'Doblo' },
    ],
  },
  {
    nameEn: 'Skoda',
    nameRu: 'Skoda',
    country: 'Czech Republic',
    models: [
      { nameEn: 'Fabia', nameRu: 'Fabia' },
      { nameEn: 'Octavia', nameRu: 'Octavia' },
      { nameEn: 'Superb', nameRu: 'Superb' },
      { nameEn: 'Kamiq', nameRu: 'Kamiq' },
      { nameEn: 'Karoq', nameRu: 'Karoq' },
      { nameEn: 'Kodiaq', nameRu: 'Kodiaq' },
      { nameEn: 'Enyaq', nameRu: 'Enyaq' },
      { nameEn: 'Scala', nameRu: 'Scala' },
    ],
  },
  {
    nameEn: 'SEAT',
    nameRu: 'SEAT',
    country: 'Spain',
    models: [
      { nameEn: 'Ibiza', nameRu: 'Ibiza' },
      { nameEn: 'Leon', nameRu: 'Leon' },
      { nameEn: 'Arona', nameRu: 'Arona' },
      { nameEn: 'Ateca', nameRu: 'Ateca' },
      { nameEn: 'Tarraco', nameRu: 'Tarraco' },
    ],
  },
  {
    nameEn: 'Opel',
    nameRu: 'Opel',
    country: 'Germany',
    models: [
      { nameEn: 'Corsa', nameRu: 'Corsa' },
      { nameEn: 'Astra', nameRu: 'Astra' },
      { nameEn: 'Insignia', nameRu: 'Insignia' },
      { nameEn: 'Mokka', nameRu: 'Mokka' },
      { nameEn: 'Crossland', nameRu: 'Crossland' },
      { nameEn: 'Grandland', nameRu: 'Grandland' },
      { nameEn: 'Combo', nameRu: 'Combo' },
    ],
  },
  {
    nameEn: 'Dodge',
    nameRu: 'Dodge',
    country: 'USA',
    models: [
      { nameEn: 'Charger', nameRu: 'Charger' },
      { nameEn: 'Challenger', nameRu: 'Challenger' },
      { nameEn: 'Durango', nameRu: 'Durango' },
      { nameEn: 'Ram 1500', nameRu: 'Ram 1500' },
      { nameEn: 'Journey', nameRu: 'Journey' },
    ],
  },
  {
    nameEn: 'GMC',
    nameRu: 'GMC',
    country: 'USA',
    models: [
      { nameEn: 'Sierra', nameRu: 'Sierra' },
      { nameEn: 'Yukon', nameRu: 'Yukon' },
      { nameEn: 'Acadia', nameRu: 'Acadia' },
      { nameEn: 'Terrain', nameRu: 'Terrain' },
      { nameEn: 'Canyon', nameRu: 'Canyon' },
    ],
  },
  {
    nameEn: 'Cadillac',
    nameRu: 'Cadillac',
    country: 'USA',
    models: [
      { nameEn: 'Escalade', nameRu: 'Escalade' },
      { nameEn: 'XT5', nameRu: 'XT5' },
      { nameEn: 'XT6', nameRu: 'XT6' },
      { nameEn: 'CT5', nameRu: 'CT5' },
      { nameEn: 'Lyriq', nameRu: 'Lyriq' },
    ],
  },
  {
    nameEn: 'Infiniti',
    nameRu: 'Infiniti',
    country: 'Japan',
    models: [
      { nameEn: 'Q50', nameRu: 'Q50' },
      { nameEn: 'Q60', nameRu: 'Q60' },
      { nameEn: 'QX50', nameRu: 'QX50' },
      { nameEn: 'QX60', nameRu: 'QX60' },
      { nameEn: 'QX80', nameRu: 'QX80' },
    ],
  },
  {
    nameEn: 'Acura',
    nameRu: 'Acura',
    country: 'Japan',
    models: [
      { nameEn: 'TLX', nameRu: 'TLX' },
      { nameEn: 'Integra', nameRu: 'Integra' },
      { nameEn: 'MDX', nameRu: 'MDX' },
      { nameEn: 'RDX', nameRu: 'RDX' },
      { nameEn: 'NSX', nameRu: 'NSX' },
    ],
  },
  {
    nameEn: 'Genesis',
    nameRu: 'Genesis',
    country: 'South Korea',
    models: [
      { nameEn: 'G70', nameRu: 'G70' },
      { nameEn: 'G80', nameRu: 'G80' },
      { nameEn: 'G90', nameRu: 'G90' },
      { nameEn: 'GV70', nameRu: 'GV70' },
      { nameEn: 'GV80', nameRu: 'GV80' },
    ],
  },
  {
    nameEn: 'Suzuki',
    nameRu: 'Suzuki',
    country: 'Japan',
    models: [
      { nameEn: 'Swift', nameRu: 'Swift' },
      { nameEn: 'Vitara', nameRu: 'Vitara' },
      { nameEn: 'Jimny', nameRu: 'Jimny' },
      { nameEn: 'Baleno', nameRu: 'Baleno' },
      { nameEn: 'S-Cross', nameRu: 'S-Cross' },
      { nameEn: 'Ignis', nameRu: 'Ignis' },
    ],
  },
  {
    nameEn: 'Dacia',
    nameRu: 'Dacia',
    country: 'Romania',
    models: [
      { nameEn: 'Sandero', nameRu: 'Sandero' },
      { nameEn: 'Duster', nameRu: 'Duster' },
      { nameEn: 'Logan', nameRu: 'Logan' },
      { nameEn: 'Jogger', nameRu: 'Jogger' },
      { nameEn: 'Spring', nameRu: 'Spring' },
    ],
  },
  {
    nameEn: 'Mini',
    nameRu: 'Mini',
    country: 'UK',
    models: [
      { nameEn: 'Cooper', nameRu: 'Cooper' },
      { nameEn: 'Countryman', nameRu: 'Countryman' },
      { nameEn: 'Clubman', nameRu: 'Clubman' },
      { nameEn: 'Convertible', nameRu: 'Convertible' },
    ],
  },
  {
    nameEn: 'Jaguar',
    nameRu: 'Jaguar',
    country: 'UK',
    models: [
      { nameEn: 'XE', nameRu: 'XE' },
      { nameEn: 'XF', nameRu: 'XF' },
      { nameEn: 'F-Pace', nameRu: 'F-Pace' },
      { nameEn: 'E-Pace', nameRu: 'E-Pace' },
      { nameEn: 'I-Pace', nameRu: 'I-Pace' },
      { nameEn: 'F-Type', nameRu: 'F-Type' },
    ],
  },
  {
    nameEn: 'Alfa Romeo',
    nameRu: 'Alfa Romeo',
    country: 'Italy',
    models: [
      { nameEn: 'Giulia', nameRu: 'Giulia' },
      { nameEn: 'Stelvio', nameRu: 'Stelvio' },
      { nameEn: 'Tonale', nameRu: 'Tonale' },
      { nameEn: 'Giulietta', nameRu: 'Giulietta' },
    ],
  },
  {
    nameEn: 'Maserati',
    nameRu: 'Maserati',
    country: 'Italy',
    models: [
      { nameEn: 'Ghibli', nameRu: 'Ghibli' },
      { nameEn: 'Quattroporte', nameRu: 'Quattroporte' },
      { nameEn: 'Levante', nameRu: 'Levante' },
      { nameEn: 'Grecale', nameRu: 'Grecale' },
      { nameEn: 'MC20', nameRu: 'MC20' },
    ],
  },
  {
    nameEn: 'Ferrari',
    nameRu: 'Ferrari',
    country: 'Italy',
    models: [
      { nameEn: 'Roma', nameRu: 'Roma' },
      { nameEn: 'Portofino', nameRu: 'Portofino' },
      { nameEn: '296 GTB', nameRu: '296 GTB' },
      { nameEn: 'SF90', nameRu: 'SF90' },
      { nameEn: 'Purosangue', nameRu: 'Purosangue' },
    ],
  },
  {
    nameEn: 'Lamborghini',
    nameRu: 'Lamborghini',
    country: 'Italy',
    models: [
      { nameEn: 'Huracan', nameRu: 'Huracan' },
      { nameEn: 'Urus', nameRu: 'Urus' },
      { nameEn: 'Revuelto', nameRu: 'Revuelto' },
      { nameEn: 'Aventador', nameRu: 'Aventador' },
    ],
  },
  {
    nameEn: 'Bentley',
    nameRu: 'Bentley',
    country: 'UK',
    models: [
      { nameEn: 'Continental GT', nameRu: 'Continental GT' },
      { nameEn: 'Flying Spur', nameRu: 'Flying Spur' },
      { nameEn: 'Bentayga', nameRu: 'Bentayga' },
    ],
  },
  {
    nameEn: 'Rolls-Royce',
    nameRu: 'Rolls-Royce',
    country: 'UK',
    models: [
      { nameEn: 'Ghost', nameRu: 'Ghost' },
      { nameEn: 'Phantom', nameRu: 'Phantom' },
      { nameEn: 'Cullinan', nameRu: 'Cullinan' },
      { nameEn: 'Spectre', nameRu: 'Spectre' },
    ],
  },
  {
    nameEn: 'BYD',
    nameRu: 'BYD',
    country: 'China',
    models: [
      { nameEn: 'Atto 3', nameRu: 'Atto 3' },
      { nameEn: 'Han', nameRu: 'Han' },
      { nameEn: 'Tang', nameRu: 'Tang' },
      { nameEn: 'Seal', nameRu: 'Seal' },
      { nameEn: 'Dolphin', nameRu: 'Dolphin' },
      { nameEn: 'Song Plus', nameRu: 'Song Plus' },
    ],
  },
  {
    nameEn: 'Geely',
    nameRu: 'Geely',
    country: 'China',
    models: [
      { nameEn: 'Coolray', nameRu: 'Coolray' },
      { nameEn: 'Atlas', nameRu: 'Atlas' },
      { nameEn: 'Monjaro', nameRu: 'Monjaro' },
      { nameEn: 'Emgrand', nameRu: 'Emgrand' },
      { nameEn: 'Tugella', nameRu: 'Tugella' },
    ],
  },
  {
    nameEn: 'Chery',
    nameRu: 'Chery',
    country: 'China',
    models: [
      { nameEn: 'Tiggo 4', nameRu: 'Tiggo 4' },
      { nameEn: 'Tiggo 7', nameRu: 'Tiggo 7' },
      { nameEn: 'Tiggo 8', nameRu: 'Tiggo 8' },
      { nameEn: 'Arrizo 6', nameRu: 'Arrizo 6' },
      { nameEn: 'Omoda 5', nameRu: 'Omoda 5' },
    ],
  },
  {
    nameEn: 'Haval',
    nameRu: 'Haval',
    country: 'China',
    models: [
      { nameEn: 'Jolion', nameRu: 'Jolion' },
      { nameEn: 'F7', nameRu: 'F7' },
      { nameEn: 'H6', nameRu: 'H6' },
      { nameEn: 'Dargo', nameRu: 'Dargo' },
      { nameEn: 'H9', nameRu: 'H9' },
    ],
  },
  {
    nameEn: 'Great Wall',
    nameRu: 'Great Wall',
    country: 'China',
    models: [
      { nameEn: 'Poer', nameRu: 'Poer' },
      { nameEn: 'Wingle', nameRu: 'Wingle' },
      { nameEn: 'Steed', nameRu: 'Steed' },
    ],
  },
  {
    nameEn: 'Isuzu',
    nameRu: 'Isuzu',
    country: 'Japan',
    models: [
      { nameEn: 'D-Max', nameRu: 'D-Max' },
      { nameEn: 'MU-X', nameRu: 'MU-X' },
      { nameEn: 'N-Series', nameRu: 'N-Series' },
      { nameEn: 'F-Series', nameRu: 'F-Series' },
    ],
  },
  {
    nameEn: 'MAN',
    nameRu: 'MAN',
    country: 'Germany',
    models: [
      { nameEn: 'TGX', nameRu: 'TGX' },
      { nameEn: 'TGS', nameRu: 'TGS' },
      { nameEn: 'TGL', nameRu: 'TGL' },
      { nameEn: 'Lion Coach', nameRu: 'Lion Coach' },
    ],
  },
  {
    nameEn: 'Scania',
    nameRu: 'Scania',
    country: 'Sweden',
    models: [
      { nameEn: 'R-Series', nameRu: 'R-Series' },
      { nameEn: 'S-Series', nameRu: 'S-Series' },
      { nameEn: 'G-Series', nameRu: 'G-Series' },
      { nameEn: 'P-Series', nameRu: 'P-Series' },
    ],
  },
  {
    nameEn: 'DAF',
    nameRu: 'DAF',
    country: 'Netherlands',
    models: [
      { nameEn: 'XF', nameRu: 'XF' },
      { nameEn: 'XG', nameRu: 'XG' },
      { nameEn: 'CF', nameRu: 'CF' },
      { nameEn: 'LF', nameRu: 'LF' },
    ],
  },
  {
    nameEn: 'Iveco',
    nameRu: 'Iveco',
    country: 'Italy',
    models: [
      { nameEn: 'Daily', nameRu: 'Daily' },
      { nameEn: 'Eurocargo', nameRu: 'Eurocargo' },
      { nameEn: 'S-Way', nameRu: 'S-Way' },
      { nameEn: 'Trakker', nameRu: 'Trakker' },
    ],
  },
  {
    nameEn: 'Harley-Davidson',
    nameRu: 'Harley-Davidson',
    country: 'USA',
    models: [
      { nameEn: 'Sportster', nameRu: 'Sportster' },
      { nameEn: 'Street Glide', nameRu: 'Street Glide' },
      { nameEn: 'Road King', nameRu: 'Road King' },
      { nameEn: 'Fat Boy', nameRu: 'Fat Boy' },
      { nameEn: 'Pan America', nameRu: 'Pan America' },
    ],
  },
  {
    nameEn: 'Yamaha',
    nameRu: 'Yamaha',
    country: 'Japan',
    models: [
      { nameEn: 'MT-07', nameRu: 'MT-07' },
      { nameEn: 'MT-09', nameRu: 'MT-09' },
      { nameEn: 'YZF-R1', nameRu: 'YZF-R1' },
      { nameEn: 'XMAX', nameRu: 'XMAX' },
      { nameEn: 'TMAX', nameRu: 'TMAX' },
      { nameEn: 'Tracer 9', nameRu: 'Tracer 9' },
    ],
  },
  {
    nameEn: 'Kawasaki',
    nameRu: 'Kawasaki',
    country: 'Japan',
    models: [
      { nameEn: 'Ninja 650', nameRu: 'Ninja 650' },
      { nameEn: 'Z900', nameRu: 'Z900' },
      { nameEn: 'Versys 650', nameRu: 'Versys 650' },
      { nameEn: 'Vulcan', nameRu: 'Vulcan' },
      { nameEn: 'KLR650', nameRu: 'KLR650' },
    ],
  },
  {
    nameEn: 'Ducati',
    nameRu: 'Ducati',
    country: 'Italy',
    models: [
      { nameEn: 'Panigale', nameRu: 'Panigale' },
      { nameEn: 'Monster', nameRu: 'Monster' },
      { nameEn: 'Multistrada', nameRu: 'Multistrada' },
      { nameEn: 'Scrambler', nameRu: 'Scrambler' },
      { nameEn: 'Diavel', nameRu: 'Diavel' },
    ],
  },
  {
    nameEn: 'KTM',
    nameRu: 'KTM',
    country: 'Austria',
    models: [
      { nameEn: '390 Duke', nameRu: '390 Duke' },
      { nameEn: '1290 Super Duke', nameRu: '1290 Super Duke' },
      { nameEn: '890 Adventure', nameRu: '890 Adventure' },
      { nameEn: 'RC 390', nameRu: 'RC 390' },
    ],
  },
  {
    nameEn: 'Lada',
    nameRu: 'Lada',
    country: 'Russia',
    models: [
      { nameEn: 'Vesta', nameRu: 'Vesta' },
      { nameEn: 'Granta', nameRu: 'Granta' },
      { nameEn: 'Niva', nameRu: 'Niva' },
      { nameEn: 'Largus', nameRu: 'Largus' },
      { nameEn: 'XRAY', nameRu: 'XRAY' },
    ],
  },
  {
    nameEn: 'UAZ',
    nameRu: 'UAZ',
    country: 'Russia',
    models: [
      { nameEn: 'Patriot', nameRu: 'Patriot' },
      { nameEn: 'Hunter', nameRu: 'Hunter' },
      { nameEn: 'Pickup', nameRu: 'Pickup' },
      { nameEn: 'Profi', nameRu: 'Profi' },
    ],
  },
  {
    nameEn: 'GAZ',
    nameRu: 'GAZ',
    country: 'Russia',
    models: [
      { nameEn: 'Gazelle Next', nameRu: 'Gazelle Next' },
      { nameEn: 'Sobol', nameRu: 'Sobol' },
      { nameEn: 'Valdai', nameRu: 'Valdai' },
    ],
  },
  {
    nameEn: 'Rivian',
    nameRu: 'Rivian',
    country: 'USA',
    models: [
      { nameEn: 'R1T', nameRu: 'R1T' },
      { nameEn: 'R1S', nameRu: 'R1S' },
      { nameEn: 'EDV', nameRu: 'EDV' },
    ],
  },
  {
    nameEn: 'Lucid',
    nameRu: 'Lucid',
    country: 'USA',
    models: [
      { nameEn: 'Air', nameRu: 'Air' },
      { nameEn: 'Gravity', nameRu: 'Gravity' },
    ],
  },
  {
    nameEn: 'Polestar',
    nameRu: 'Polestar',
    country: 'Sweden',
    models: [
      { nameEn: 'Polestar 2', nameRu: 'Polestar 2' },
      { nameEn: 'Polestar 3', nameRu: 'Polestar 3' },
      { nameEn: 'Polestar 4', nameRu: 'Polestar 4' },
    ],
  },
  {
    nameEn: 'SsangYong',
    nameRu: 'SsangYong',
    country: 'South Korea',
    models: [
      { nameEn: 'Rexton', nameRu: 'Rexton' },
      { nameEn: 'Korando', nameRu: 'Korando' },
      { nameEn: 'Tivoli', nameRu: 'Tivoli' },
      { nameEn: 'Musso', nameRu: 'Musso' },
    ],
  },
  {
    nameEn: 'Proton',
    nameRu: 'Proton',
    country: 'Malaysia',
    models: [
      { nameEn: 'Saga', nameRu: 'Saga' },
      { nameEn: 'Persona', nameRu: 'Persona' },
      { nameEn: 'X50', nameRu: 'X50' },
      { nameEn: 'X70', nameRu: 'X70' },
    ],
  },
  {
    nameEn: 'Mahindra',
    nameRu: 'Mahindra',
    country: 'India',
    models: [
      { nameEn: 'Scorpio', nameRu: 'Scorpio' },
      { nameEn: 'XUV700', nameRu: 'XUV700' },
      { nameEn: 'Thar', nameRu: 'Thar' },
      { nameEn: 'Bolero', nameRu: 'Bolero' },
    ],
  },
  {
    nameEn: 'Tata',
    nameRu: 'Tata',
    country: 'India',
    models: [
      { nameEn: 'Nexon', nameRu: 'Nexon' },
      { nameEn: 'Harrier', nameRu: 'Harrier' },
      { nameEn: 'Safari', nameRu: 'Safari' },
      { nameEn: 'Punch', nameRu: 'Punch' },
    ],
  },
];

// Expand model count with trim / generation variants for bulk data realism
export const modelVariants = ['Base', 'Comfort', 'Premium', 'Sport', 'Limited', 'Touring', 'Executive'];

export function expandManufacturersWithVariants(
  base: ManufacturerSeed[],
  variantCount = 2,
): ManufacturerSeed[] {
  return base.flatMap((mfr) => {
    const expandedModels = mfr.models.flatMap((model) => {
      const variants = [model];
      for (let i = 0; i < variantCount; i++) {
        const variantName = modelVariants[i % modelVariants.length];
        variants.push({
          nameEn: `${model.nameEn} ${variantName}`,
          nameRu: `${model.nameRu} ${variantName}`,
        });
      }
      return variants;
    });
    return [{ ...mfr, models: expandedModels }];
  });
}
