export type Bilingual = { nameEn: string; nameRu: string };

export const vehicleCategories: Array<Bilingual & { slug: string }> = [
  { nameEn: 'Cars', nameRu: 'Автомобили', slug: 'cars' },
  { nameEn: 'Custom Vehicles', nameRu: 'Спецтехника', slug: 'custom-vehicles' },
  { nameEn: 'Motorcycles', nameRu: 'Мотоциклы', slug: 'motorcycles' },
];

export const bodyTypes: Bilingual[] = [
  // Cars
  { nameEn: 'Sedan', nameRu: 'Седан' },
  { nameEn: 'Jeep', nameRu: 'Джип' },
  { nameEn: 'SUV', nameRu: 'Внедорожник' },
  { nameEn: 'Coupe', nameRu: 'Купе' },
  { nameEn: 'Hatchback', nameRu: 'Хэтчбек' },
  { nameEn: 'Universal', nameRu: 'Универсал' },
  { nameEn: 'Wagon', nameRu: 'Универсал Wagon' },
  { nameEn: 'Cabriolet', nameRu: 'Кабриолет' },
  { nameEn: 'Convertible', nameRu: 'Кабриолет Convertible' },
  { nameEn: 'Pickup', nameRu: 'Пикап' },
  { nameEn: 'Minivan', nameRu: 'Минивэн' },
  { nameEn: 'Van', nameRu: 'Фургон Van' },
  { nameEn: 'MPV', nameRu: 'Минивэн MPV' },
  { nameEn: 'Limousine', nameRu: 'Лимузин' },
  { nameEn: 'Crossover', nameRu: 'Кроссовер' },
  { nameEn: 'Roadster', nameRu: 'Родстер' },
  { nameEn: 'Microcar', nameRu: 'Микроавтомобиль' },
  { nameEn: 'Liftback', nameRu: 'Лифтбек' },
  { nameEn: 'Fastback', nameRu: 'Фастбек' },
  { nameEn: 'Hardtop', nameRu: 'Хардтоп' },
  { nameEn: 'Shooting Brake', nameRu: 'Шутинг-брейк' },
  { nameEn: 'Panel Van', nameRu: 'Цельнометаллический фургон' },
  { nameEn: 'Chassis Cab', nameRu: 'Шасси' },
  { nameEn: 'Bus', nameRu: 'Автобус' },
  { nameEn: 'Minibus', nameRu: 'Микроавтобус' },
  // Custom vehicles
  { nameEn: 'Semi-trailer truck', nameRu: 'Седельный тягач' },
  { nameEn: 'Truck', nameRu: 'Грузовик' },
  { nameEn: 'Dump truck', nameRu: 'Самосвал' },
  { nameEn: 'Box Truck', nameRu: 'Бортовой грузовик' },
  { nameEn: 'Tractor Unit', nameRu: 'Тягач' },
  { nameEn: 'Agricultural', nameRu: 'Сельхозтехника' },
  { nameEn: 'Cranes', nameRu: 'Краны' },
  { nameEn: 'Excavators', nameRu: 'Экскаваторы' },
  { nameEn: 'Custom machinery', nameRu: 'Спецтехника' },
  { nameEn: 'Trailer', nameRu: 'Прицеп' },
  { nameEn: 'Loader', nameRu: 'Погрузчик' },
  { nameEn: 'Concrete pump truck', nameRu: 'Бетононасос' },
  { nameEn: 'Road', nameRu: 'Дорожная техника' },
  { nameEn: 'Warehouse truck', nameRu: 'Складской погрузчик' },
  // Motorcycles
  { nameEn: 'Motorcycle', nameRu: 'Мотоцикл' },
  { nameEn: 'Scooter', nameRu: 'Скутер' },
  { nameEn: 'Quad bike', nameRu: 'Квадроцикл' },
  { nameEn: 'Water transport', nameRu: 'Водный транспорт' },
  { nameEn: 'Tricycle', nameRu: 'Трицикл' },
  { nameEn: 'Buggy', nameRu: 'Багги' },
  { nameEn: 'Snowmobile', nameRu: 'Снегоход' },
  { nameEn: 'Trailer for boat', nameRu: 'Прицеп для лодки' },
  { nameEn: 'Trailer for motorcycle', nameRu: 'Прицеп для мотоцикла' },
  { nameEn: 'Karting-car', nameRu: 'Карт' },
];

export const fuelTypes: Bilingual[] = [
  { nameEn: 'Petrol', nameRu: 'Бензин' },
  { nameEn: 'Diesel', nameRu: 'Дизель' },
  { nameEn: 'Hybrid', nameRu: 'Гибрид' },
  { nameEn: 'Electric', nameRu: 'Электрический' },
  { nameEn: 'LPG', nameRu: 'Газ (LPG)' },
  { nameEn: 'CNG', nameRu: 'Газ (CNG)' },
  { nameEn: 'Plug-in Hybrid', nameRu: 'Подключаемый гибрид' },
  { nameEn: 'Hydrogen', nameRu: 'Водородный' },
  { nameEn: 'Mild Hybrid', nameRu: 'Мягкий гибрид' },
  { nameEn: 'E85 Flex Fuel', nameRu: 'E85' },
  { nameEn: 'Biofuel', nameRu: 'Биотопливо' },
];

export const transmissions: Bilingual[] = [
  { nameEn: 'Automatic', nameRu: 'Автомат' },
  { nameEn: 'Manual', nameRu: 'Механика' },
  { nameEn: 'CVT', nameRu: 'Вариатор' },
  { nameEn: 'Semi-automatic', nameRu: 'Полуавтомат' },
  { nameEn: 'Tiptronic', nameRu: 'Типтроник' },
  { nameEn: 'Robot', nameRu: 'Робот' },
  { nameEn: 'DCT', nameRu: 'Робот DCT' },
  { nameEn: 'AMT', nameRu: 'Робот AMT' },
  { nameEn: 'Single-speed', nameRu: 'Одноступенчатая (EV)' },
];

export const driveTypes: Bilingual[] = [
  { nameEn: 'Front-wheel drive', nameRu: 'Передний привод' },
  { nameEn: 'Rear-wheel drive', nameRu: 'Задний привод' },
  { nameEn: 'All-wheel drive', nameRu: 'Полный привод' },
  { nameEn: '4WD', nameRu: '4WD' },
  { nameEn: 'AWD with lock', nameRu: 'Полный с блокировкой' },
  { nameEn: '6x6', nameRu: '6x6' },
];

export const colors: Array<Bilingual & { hex: string }> = [
  { nameEn: 'Black', nameRu: 'Чёрный', hex: '#000000' },
  { nameEn: 'White', nameRu: 'Белый', hex: '#FFFFFF' },
  { nameEn: 'Silver', nameRu: 'Серебристый', hex: '#C0C0C0' },
  { nameEn: 'Grey', nameRu: 'Серый', hex: '#808080' },
  { nameEn: 'Red', nameRu: 'Красный', hex: '#FF0000' },
  { nameEn: 'Blue', nameRu: 'Синий', hex: '#0000FF' },
  { nameEn: 'Green', nameRu: 'Зелёный', hex: '#008000' },
  { nameEn: 'Yellow', nameRu: 'Жёлтый', hex: '#FFFF00' },
  { nameEn: 'Orange', nameRu: 'Оранжевый', hex: '#FFA500' },
  { nameEn: 'Brown', nameRu: 'Коричневый', hex: '#8B4513' },
  { nameEn: 'Beige', nameRu: 'Бежевый', hex: '#F5F5DC' },
  { nameEn: 'Gold', nameRu: 'Золотой', hex: '#FFD700' },
  { nameEn: 'Purple', nameRu: 'Фиолетовый', hex: '#800080' },
  { nameEn: 'Burgundy', nameRu: 'Бордовый', hex: '#800020' },
  { nameEn: 'Navy Blue', nameRu: 'Тёмно-синий', hex: '#000080' },
  { nameEn: 'Sky Blue', nameRu: 'Голубой', hex: '#87CEEB' },
  { nameEn: 'Teal', nameRu: 'Бирюзовый', hex: '#008080' },
  { nameEn: 'Champagne', nameRu: 'Шампань', hex: '#F7E7CE' },
  { nameEn: 'Pearl White', nameRu: 'Жемчужно-белый', hex: '#F8F6F0' },
  { nameEn: 'Graphite', nameRu: 'Графит', hex: '#383838' },
  { nameEn: 'Bronze', nameRu: 'Бронза', hex: '#CD7F32' },
  { nameEn: 'Copper', nameRu: 'Медный', hex: '#B87333' },
  { nameEn: 'Matte Black', nameRu: 'Матовый чёрный', hex: '#1C1C1C' },
  { nameEn: 'Lime Green', nameRu: 'Салатовый', hex: '#32CD32' },
  { nameEn: 'Pink', nameRu: 'Розовый', hex: '#FFC0CB' },
];
